- name: consul server
  hosts: _server
  remote_user: ubuntu
  become: yes
  vars:
    - server: true
  tasks:
   - name: consul role - for server
     include_role:
       name: consul-role

- name: consul client - jenkins
  hosts: _jenkins
  remote_user: ubuntu
  become: yes
  vars:
    - server: false
    - service_port: 8080
    - service_name : 'Jenkins-Service'
    - service_tags : 'Jenkins-Service'
    - check_id : "tcp-{{ service_name }}"
    - check_name : "tcp-{{ service_port }}"
    - check_tcp : "localhost:{{ service_port }}"
    - add_service : true
  tasks:
   - name: consul role - for client
     include_role:
       name: consul-role

- name: consul client - ELK
  hosts: _elk
  remote_user: ubuntu
  become: yes
  vars:
    - server: false
    - service_port: 5601
    - service_name : 'ELK-Service'
    - service_tags : 'ELK-Service'
    - check_id : "tcp-{{ service_name }}"
    - check_name : "tcp-{{ service_port }}"
    - check_tcp : "localhost:{{ service_port }}"
    - add_service : true
  tasks:
   - name: consul role - for client
     include_role:
       name: consul-role
  

- name: consul users
  hosts: _ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
   - name: restart consul
     service:
      name: consul
      state: restarted
      enabled : yes