---
- name: Create consul folder and tmp folder
  file:
    path: "/tmp"
    state: directory   

- name: Fetching consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/consul.zip

- name: Unarchive consul
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Change the permissions of consul
  file:
    path: /usr/local/bin/consul
    mode: +x

- name: Create folders - /opt/consul - /etc/consul.d - /run/consul
  file:
    path: "{{ folder_item2 }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  with_items: 
   - /opt/consul
   - /etc/consul.d
   - /run/consul
  loop_control:
    loop_var: folder_item2

- debug:
    var: server 

- debug:
    var: service_name 

- name: add service
  template:
    src: templates/service.json.j2
    dest: "/etc/consul.d/jenkins_server_service.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  when: add_service|bool == true

- name: Create configuration
  template:
    src: templates/config.json.j2
    dest: "/etc/consul.d/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644


- name: Create consul.service
  template:
    src: templates/consul.service.j2
    dest: "/etc/systemd/system/consul.service"
    mode: 0644
  notify: restart consul

- name: Just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes

- name: Enable consul service
  systemd:
    service: consul.service
    enabled: true

- name: start consul
  systemd:
    name: consul
    state: started




