---
- name: Update the apt package
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install unzip
  apt: 
    name : "unzip={{ unzip_version }}"
    state : present 
    force_apt_get : true

- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present
    force_apt_get : true

- name: Configuring dnsmasq
  template:
    src: 10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    mode: 0644

- name: start dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: Create Dnsmasq configuration
  template:
    src: resolved.j2
    dest: /etc/systemd/resolved.conf
    mode: 0644
  notify: restart dnsmsystemd-resolved.service

- name: restart dnsmsystemd-resolved.service
  systemd:
    name: systemd-resolved.service
    state: restarted