{
 "title": "Kandula Visitors",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "5Min increase in visitors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"home.html\"}[5m])",
     "legendFormat": "home.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"instances.html\"}[5m])",
     "legendFormat": "instances.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"scheduler.html\"}[5m])",
     "legendFormat": "scheduler.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"metrics.html\"}[5m])",
     "legendFormat": "metrics.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"health.html\"}[5m])",
     "legendFormat": "health.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"about.html\"}[5m])",
     "legendFormat": "about.html"
    }
   ]
  },
  {
   "title": "1Hours increase in visitors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"home.html\"}[1h])",
     "legendFormat": "home.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"instances.html\"}[1h])",
     "legendFormat": "instances.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"scheduler.html\"}[1h])",
     "legendFormat": "scheduler.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"metrics.html\"}[1h])",
     "legendFormat": "metrics.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"health.html\"}[1h])",
     "legendFormat": "health.html"
    },
    {
     "expr": "increase(kandula_request_count_pages_total{page_name=\"about.html\"}[1h])",
     "legendFormat": "about.html"
    }
   ]
  },
  {
   "title": "5Min increase in visitors On All Pages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kandula_request_count_pages_total[5m]))",
     "legendFormat": "All"
    }
   ]
  }
 ]
}