
apiVersion: v1
kind: ConfigMap
metadata:
  name: "prometheus-datasource"
  namespace: monitoring
  labels:
    grafana_datasource: "true"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: 'http://af4acbf8b6a79488a8832a6ab77faaca-1110326338.us-east-1.elb.amazonaws.com'
      access: proxy
      isDefault: true