
apiVersion: v1
kind: ConfigMap
metadata:
  name: "prometheus-datasource"
  namespace: monitoring
  labels:
    grafana_datasource: "true"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: 'http://myprom-prometheus-server.monitoring.svc.cluster.local'
      access: proxy
      isDefault: true