- set_fact:
    ELK_IP: "{{ lookup('ini', 'ELK_IP type=properties file=/home/ubuntu/configs_for_ansible.ini') }}"
- debug:
    var: ELK_IP

- name: create filebeat yml
  template:
    src: /home/ubuntu/Ansible-Part/k8s-role/templates/filebeat_deployment.yml.j2
    dest: "/home/ubuntu/filebeat_deployment.yml"

- name: filebeat Deployment from file
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/filebeat_deployment.yml

- name: Create  Deployment of elastic search
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/deploy_es.yml