---
- name: Add grafana helm repo
  kubernetes.core.helm_repository:
    name: "{{ my_grafana_chart_name }}"
    repo_url: "{{ grafana_helm_chart_url }}"

- name: save prometheus lb address to a variable
  shell: kubectl get svc myprom-prometheus-server -n monitoring -o jsonpath="{.status.loadBalancer.ingress[*]['ip', 'hostname']}"
  register: prom_lb

- set_fact:
    PROM__LB: "{{ prom_lb.stdout }}"
- debug:
    var: PROM__LB

- name: create grafana datasources yml
  template:
    src: /home/ubuntu/Ansible-Part/k8s-role/templates/grafana_datasources.yml.j2
    dest: "/home/ubuntu/Ansible-Part/deployments/grafana_datasources1.yml"

- name: deploy grafana datasources yml
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/grafana_datasources.yml

- name: deploy grafana dashboards yml
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/grafana_dashboards.yml

- name: deploy grafana dashboards yml
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/grafana_dashboards1.yml

- name: Deploy grafana chart using values files on target
  kubernetes.core.helm:
    name: "{{ my_grafana_name }}"
    chart_ref: "{{ grafana_chart_name }}"
    release_namespace: "{{ monitoring_namespcae }}"
    values_files:
      - "{{ grafana_values_path }}"
