---
- name: Add consul helm repo
  kubernetes.core.helm_repository:
    name: "{{ my_grafana_name }}"
    repo_url: "{{ grafana_helm_chart_url }}"

- name: Deploy consul chart using values files on target
  kubernetes.core.helm:
    name: "{{ my_grafana_name }}"
    chart_ref: "{{ grafana_chart_name }}"
    release_namespace: "{{ monitoring_namespcae }}"
    values_files:
      - "{{ grafana_values_path }}"