---
- name: Add consul helm repo
  kubernetes.core.helm_repository:
    name: "{{ my_grafana_chart_name }}"
    repo_url: "{{ grafana_helm_chart_url }}"

- name: Deploy consul chart using values files on target
  kubernetes.core.helm:
    name: "{{ my_grafana_name }}"
    chart_ref: "{{ grafana_chart_name }}"
    release_namespace: "{{ monitoring_namespcae }}"
    values_files:
      - "{{ grafana_values_path }}"

- name: save grafana lb address to a variable
  shell: kubectl get svc mygrafana-lb -o jsonpath="{.status.loadBalancer.ingress[*]['ip', 'hostname']}"
  register: grafana_lb

- name: Send a message with a link using Slack - grafana lb
  slack:
    token: thetoken/generatedby/slack
    msg: We sent this message using <{{ grafana_lb }}>!
    color: '#0097b3'