---
- name: connect to k8s
  shell: aws eks --region=us-east-1 update-kubeconfig --name opsschool-eks-alina--final-project

- name: Download the helm.
  get_url: url=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 dest=/home/ubuntu/get_helm.sh

- name: Change permission on get_helm.sh file
  file:
    path: /home/ubuntu/get_helm.sh
    state: file
    mode: 0700

- name: install helm
  shell: /home/ubuntu/get_helm.sh

- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: "{{ monitoring_namespcae }}"
    api_version: v1
    kind: Namespace
    state: present

# tasks file for consul-role
- name: create and deploy all needed helm charts
  include_tasks: "{{ item }}"
  loop:
    - consul_main.yml
    - prom_main.yml
    - grafana_main.yml
    - filebeat_main.yml

- name: Download metrics-server manifest to the cluster.
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: /home/ubuntu/Ansible-Part/deployments/metrics_server.yaml
    mode: '0664'

- name: Apply metrics-server manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/metrics_server.yaml

- name: kandula hpa Deployment from file
  kubernetes.core.k8s:
    state: present
    src: /home/ubuntu/Ansible-Part/deployments/hpa_kandula.yml




