---
# tasks file for consul-role
- name: create and deploy all needed helm charts
  include_tasks: "{{ item }}"
  loop:
    - preparations_main.yml
    - consul_main.yml
    - prom_main.yml
    - grafana_main.yml
    - miscellaneous_main.yml






