global:
  enabled: false
  image: "hashicorp/consul:1.11.3"
  datacenter: alina_consul
  gossipEncryption:
    # secretName is the name of the Kubernetes secret that holds the gossip
    # encryption key. The secret must be in the same namespace that Consul is installed into.
    secretName: "consul-gossip-encryption-key"
    # secretKey is the key within the Kubernetes secret that holds the gossip
    # encryption key.
    secretKey: "key"
# Values that configure running a Consul client on Kubernetes nodes.
client:
  enabled: true
  join:
    - "provider=aws tag_key=consul_connect tag_value=true"
dns:
  # @type: boolean
  enabled: true
syncCatalog:
  # True if you want to enable the catalog sync. Set to "-" to inherit from
  # global.enabled.
  enabled: true