apiVersion: v1
kind: Service
metadata:
  name: kandula-lb
  labels:
    app: kandula
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: kandula
  type: LoadBalancer